// <auto-generated />
using ElevatorSim.Persistence.ElevatorModelPersistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElevatorSim.Persistence.ElevatorModelPersistence.Migrations
{
    [DbContext(typeof(ElevatorContext))]
    [Migration("20230302184547_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ElevatorSim.Domain.DomainModel.ElevatorModel.Elevator", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("CurrentFloor")
                        .HasColumnType("bigint");

                    b.Property<long>("CurrentWeight")
                        .HasColumnType("bigint");

                    b.Property<string>("ElevatorStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<long>("Weightlimit")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Elevator");
                });
#pragma warning restore 612, 618
        }
    }
}
